@startuml

package "Présentation" {
  [VenteController] <<Controller>>
  [RapportController] <<Controller>>
  [StockCentralController] <<Controller>>
  [Thymeleaf] <<View>>
}

package "Logique Métier" {
  [MagasinService] <<Service>>
  [StockCentralService] <<Service>>
  [VenteService] <<Service>>
}

package "Persistance" {
  [MagasinRepository] <<Repository>>
  [VenteRepository] <<Repository>>
  [StockCentralRepository] <<Repository>>
  [DemandeReapprovisionnementRepository] <<Repository>>
  [ProduitRepository] <<Repository>>
  [StockMagasinRepository] <<Repository>>
}
package "Base de données" {
  [PostgreSQL] <<Database>>
}
[VenteController] -up-> [Thymeleaf]
[RapportController] -up-> [Thymeleaf]
[StockCentralController] -up-> [Thymeleaf]

[VenteController] --> [VenteService]
[RapportController] --> [MagasinService]
[StockCentralController] --> [MagasinService]
[RapportController] --> [VenteService]
[StockCentralController] --> [StockCentralService]


[MagasinService] --> [MagasinRepository]
[MagasinService] --> [DemandeReapprovisionnementRepository]
[StockCentralService] --> [StockCentralRepository]
[StockCentralService] --> [DemandeReapprovisionnementRepository]
[StockCentralService] --> [ProduitRepository]
[StockCentralService] --> [MagasinRepository]
[VenteService] --> [VenteRepository]
[VenteService] --> [MagasinRepository]
[VenteService] --> [ProduitRepository]
[VenteService] --> [StockMagasinRepository]

[MagasinRepository] --> [PostgreSQL]
[VenteRepository] --> [PostgreSQL]
[StockCentralRepository] --> [PostgreSQL]
[DemandeReapprovisionnementRepository] --> [PostgreSQL]
[ProduitRepository] --> [PostgreSQL]
[StockMagasinRepository] --> [PostgreSQL]
@enduml