@startuml

package "Présentation" {
  [ProduitController] <<Controller>>
  [VenteController] <<Controller>>
  [RetourController] <<Controller>>
  [Thymeleaf] <<View>>
}

package "Logique Métier" {
  [ProduitService] <<Service>>
  [VenteService] <<Service>>
  [RetourService] <<Service>>
}

package "Persistance" {
  [ProduitRepository] <<Repository>>
  [VenteRepository] <<Repository>>
  [RetourRepository] <<Repository>>
}
package "Base de données" {
  [PostgreSQL] <<Database>>
}
[ProduitController] -up-> [Thymeleaf]
[VenteController] -up-> [Thymeleaf]
[RetourController] -up-> [Thymeleaf]

[ProduitController] --> [ProduitService]
[VenteController] --> [VenteService]
[RetourController] --> [RetourService]

[ProduitService] --> [ProduitRepository]
[VenteService] --> [VenteRepository]
[RetourService] --> [RetourRepository]

[ProduitRepository] --> [PostgreSQL]
[VenteRepository] --> [PostgreSQL]
[RetourRepository] --> [PostgreSQL]
@enduml