@startuml DiagrammeClasses

class Utilisateur {
  - id: int
  - nom: string
  - email: string
}
class Produit {
  - id: int
  - nom: string
  - categorie: string
  - prix: float
  - quantite: int
}

class LigneVente {
  - idProduit: int
  - idVente: int
  - quantite: int
}

class Vente {
  - id: int
  - idUtilisateur: int
  - date: Date
  - produits: List<LigneVente>
  - total: float
}

class Retour {
  - id: int
  - idVente: int
  - dateRetour: Date
  - motif: string
}

Produit "1" --> "1" LigneVente : référencé dans >
Vente "1" *-- "*" LigneVente : contient >
Retour "1" --> "1" Vente : annule >
Utilisateur "1" --> "*" Vente : effectue >
Utilisateur "1" --> "*" Retour : effectue >
Utilisateur "1" --> "*" Produit : consulte >
@enduml
