@startuml DiagrammeDeploiement

node "Load Balancer" {
  component "NGINX" <<LoadBalancer>>
}

node "API Gateway Server" {
  component "API Gateway" <<Gateway>>
}

node "Saga Orchestrator" {
  component "SagaOrchestrator" <<Service>>
}

node "Microservice Vente" {
  component "VenteController" <<RestController>>
  component "VenteService" <<Service>>
  component "VenteRepository" <<Repository>>
}

node "Microservice Produit" {
  component "ProduitController" <<RestController>>
  component "ProduitService" <<Service>>
  component "ProduitRepository" <<Repository>>
}

node "Microservice Stock" {
  component "StockController" <<RestController>>
  component "StockService" <<Service>>
  component "StockRepository" <<Repository>>
}

node "Microservice Rapport" {
  component "RapportController" <<RestController>>
  component "RapportService" <<Service>>
  component "RapportRepository" <<Repository>>
}

node "Cache Server" {
  component "Redis" <<Cache>>
}

node "Monitoring Server" {
  component "Prometheus" <<Monitoring>>
  component "Grafana" <<Dashboard>>
}

node "Database Produit" {
  component "Produit_PostgreSQL" <<Database>>
}

node "Database Vente" {
  component "Vente_PostgreSQL" <<Database>>
}

node "Database Stock" {
  component "Stock_PostgreSQL" <<Database>>
}
node "Database Rapport" {
  component "Rapport_PostgreSQL" <<Database>>
}

' Connexions principales
"NGINX" --> "API Gateway"
"API Gateway" --> "SagaOrchestrator"

"SagaOrchestrator" --> "VenteService"
"SagaOrchestrator" --> "ProduitService"
"SagaOrchestrator" --> "StockService"
"SagaOrchestrator" --> "RapportService"

' Accès au cache
"VenteService" ..> "Redis"
"ProduitService" ..> "Redis"
"StockService" ..> "Redis"
"RapportService" ..> "Redis"

' Monitoring
"Prometheus" ..> "API Gateway"
"Prometheus" ..> "VenteService"
"Prometheus" ..> "ProduitService"
"Prometheus" ..> "StockService"
"Prometheus" ..> "RapportService"
"Prometheus" ..> "SagaOrchestrator"
"Grafana" ..> "Prometheus"
"VenteRepository" ..> "Vente_PostgreSQL"
"ProduitRepository" ..> "Produit_PostgreSQL"
"StockRepository" ..> "Stock_PostgreSQL"
"RapportRepository" ..> "Rapport_PostgreSQL"

@enduml