@startuml
actor Utilisateur
participant "RapportController" as Controller
participant "VenteService" as VenteService

Utilisateur -> Controller : GET /rapports/rapportDetaille
activate Controller

Controller -> VenteService : getVentesParMagasin()
VenteService --> Controller : Map<Magasin, List<Vente>>

Controller -> VenteService : getProduitsLesPlusVendus(1)
VenteService --> Controller : List<Entry<Produit, Integer>>

Controller -> VenteService : getStocksRestantsParMagasin()
VenteService --> Controller : Map<Magasin, List<StockMagasin>>

Controller --> Utilisateur : retourne la vue "rapportDetaille"
deactivate Controller
@enduml