name: Maven CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: mvn checkstyle:check

  build:
    name: Build and test
    runs-on: ubuntu-latest
    needs: [Lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean install -DskipTests
      - name: Run tests
        run: mvn test
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: |
          docker build -t anass1707/log430_labos:v0 .